### PR TITLE
minor improvements

### PR DESCRIPTION
**Pull request by J-N-K**
Signed-off-by: Jan N. Klug <github@klug.nrw>

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]
Thanks for the help!

I would prefer to initialize the lock object in the `OpenHABGraalJSScriptEngine` and then pass it to the `JSScriptServiceUtil` and `ThreadsafeTimers`, because this is more logically for me. The lock is shared in the engine, therefore I would like to initi it there.

I would also prefer to pass the lock and the `JSScriptServiceUtil` to the runtime features instead of the ThreadsafeTimers, as the idea of the runtime feature class is to easyily add features to the runtime by only modifyng that class. If I need parts of the ServiceUtil, I then need to modify more than one class.

I will add those changes to your PR and let you give feedback before I merge.

**Comment by florian-h05** [comment]
EDIT: I cannot edit here, I'll merge and then add my changes as a new commit - if you don't like it, I can revert.

**Comment by J-N-K** [comment]
I guess that depends on the point of view. I would say the lock is a property of the timers and acquired by the script engine, so it belongs to the timers. But that‘s up to you. I don‘t have a say in openhab-addons anyway 😀

**Comment by florian-h05** [comment]
Yes, it really depends on the point of view.
It might be true that you don't have a say, but you have much experience and therefore many will consider your opinion as relevant.

**Pull request merged**
